### ISSUE TITLE
Suggestion: Delete old nand files after conversion

### ISSUE THREAD

**Issue by supernoodled** [TheyKilledKenny/Emutool#1]
After conversion, the tool will leave the old files alone. This can be an issue if the SD card and or partition is too small, as emunands take up quite a bit of space. It would be best to delete the files while converting, but you could also just delete them after the conversion.

It could be an optional thing instead too, but meh whatever you feel like's best go with it.

I don't know anything about VBA, but if it's similar to C# then it should just be as simple as first checking whether the file (and converted file) exists, then deleting the old file.

**Comment by TheyKilledKenny** [comment]
I understand that you would like the ability to delete files after they have been restored to a SD partition, is this correct?
If so, in my opinion it's a bit risky... What if the restored partition is bad due to data corruption?
In this case it would also be necessary to include a verification of the writing before delete the source file, but this would almost double the copy time.

Let me know your opinion.

**Comment by TheyKilledKenny** [comment]
seems not a real issues.
